// data.js
const translations = {
    es: {
        // Navegación
        nav_home: "Inicio",
        nav_about: "Somos Mate",
        nav_projects: "Experiencia",
        nav_services: "Servicios",
        nav_contact: "Contáctanos",
        submenu_about_top: "Inicio",
        submenu_about_history: "Nuestra Historia",
        submenu_about_mission: "Misión y Visión",
        submenu_about_team: "Nuestro Equipo",
        submenu_about_milestones: "Hitos Institucionales",
        submenu_about_work: "Cómo trabajamos",
        submenu_about_alliances: "Alianzas",
        submenu_services_longevity: "Longevidad, Bienestar y Cuidado",
        submenu_services_economic: "Inclusión Económica y Autonomía Financiera",

        // --- PÁGINA: INDEX (HOME) ---
        // Inicio
        meta_title_index: "MATE | Inversiones & Negocios",
        meta_desc_index: "Impulsamos inclusión económica y ciudadanía inclusiva a través de soluciones productivas, financieras, sociales y sostenibles.",
        // 1.1 Hero Section        
        hero_badge_text: "Transformación Social",
        hero_title_p1: "Más capacidades.<br />Más Oportunidades.<br />Más Bienestar.",
        hero_title_p2: "",
        hero_subtitle: "En MATE conectamos territorios, personas y actores para impulsar oportunidades, transformar realidades de la mano de las comunidades y generar bienestar a lo largo de la vida.",
        hero_btn_1: "Conoce nuestras soluciones",
        hero_btn_2: "Hablemos de una alianza",

        // --- PÁGINA: SOMOS MATE ---
        // Somos Mate
        meta_title_somos: "Somos MATE | Inversiones & Negocios",
        meta_desc_somos: "Conoce a MATE, nuestra historia, misión, visión y el equipo interdisciplinario que impulsa la inclusión económica.",
        // Experiencia
        meta_title_experiencia: "Experiencia | MATE Inversiones & Negocios",
        meta_desc_experiencia: "Conoce la experiencia y las soluciones de MATE en inclusión productiva, financiera, fortalecimiento social y sostenibilidad.",
        meta_title_servicios: "Servicios | MATE Inversiones & Negocios",
        meta_desc_servicios: "Conoce los servicios de MATE en longevidad, bienestar, cuidado, inclusión económica y autonomía financiera.",
        // Contacto
        meta_title_contacto: "Contacto | MATE Inversiones & Negocios",
        meta_desc_contacto: "Ponte en contacto con MATE Inversiones & Negocios. Escríbenos para conversar sobre alianzas y proyectos.",

        // Index - Hero
        hero_title: "Más capacidades.<br />Más Oportunidades.<br />Más Bienestar.",
        hero_subtitle: "En MATE conectamos territorios, personas y actores para impulsar oportunidades, transformar realidades de la mano de las comunidades y generar bienestar a lo largo de la vida.",
        services_hero_title: "Servicios",
        services_hero_desc: "Diseñamos soluciones para transformar capacidades en oportunidades y oportunidades en bienestar.",
        services_section_label: "Servicios MATE",
        services_longevity_title: "Longevidad, Bienestar y Cuidado",
        services_longevity_text: "En MATE, entendemos la longevidad desde una perspectiva de curso de vida y por ello acompañamos a las personas en cada etapa, fortaleciendo sus capacidades, bienestar, autonomía y participación para que puedan vivir mejor, durante más tiempo y con mayores oportunidades. Para llevarlo a cabo diseñamos soluciones que conectan <strong>bienestar, cuidado, autonomía y protección</strong> desde la niñez y la juventud hasta las etapas más avanzadas de la vida.",
        services_economic_title: "Inclusión Económica y Autonomía Financiera",
        services_economic_text_1: "Diseñamos e implementamos soluciones para que personas, hogares, emprendimientos, empresas y organizaciones fortalezcan sus capacidades, generen ingresos, tomen mejores decisiones y accedan a oportunidades económicas y financieras de manera sostenible.",
        services_economic_text_2: "Integramos inclusión financiera, desarrollo empresarial, acceso a mercados, tecnología, datos y ciencias del comportamiento, adaptando cada solución a las capacidades, barreras y oportunidades de las personas y los territorios.",
        services_economic_what_we_do: "¿Qué hacemos?",
        services_economic_card1_title: "Inclusión financiera",
        services_economic_card1_desc: "Diseñamos soluciones que amplían el acceso, uso y aprovechamiento efectivo de <strong>ahorro, crédito, seguros, pagos, inversión y otros servicios financieros</strong>, conectándolos con las necesidades y capacidades reales de las personas y los negocios.",
        services_economic_card2_title: "Educación y capacidades financieras",
        services_economic_card2_desc: "Desarrollamos metodologías presenciales, digitales e híbridas para fortalecer conocimientos, comportamientos y decisiones sobre <strong>ingresos, ahorro, crédito, endeudamiento, protección, inversión y bienestar financiero</strong>.",
        services_economic_card3_title: "Autonomía económica y generación de ingresos",
        services_economic_card3_desc: "Diseñamos rutas que fortalecen capacidades, ingresos, activos productivos y autonomía económica, especialmente para poblaciones que enfrentan mayores barreras de acceso a oportunidades.",
        services_business_label: "EMPRESA MATE",
        services_business_title: "Desarrollo y fortalecimiento empresarial",
        services_business_intro_1: "Nuestro modelo de acompañamiento empresarial parte de una premisa: <strong>cada empresa tiene capacidades, desafíos y oportunidades diferentes; por eso, no todas necesitan la misma ruta.</strong>",
        services_business_intro_2: "A través del Índice de Capacidades Empresariales, diagnosticamos integralmente el negocio, identificamos fortalezas y brechas y construimos una ruta personalizada de fortalecimiento.",
        services_business_model_desc: "Integramos registro financiero permanente, asistencia modular, formación, herramientas de gestión, mentoría y consejo asesor, ciencias del comportamiento y conexión con redes y mercados, acompañando a las empresas desde el diagnóstico hasta la implementación y medición de resultados.",
        services_business_process: "Diagnosticamos → priorizamos → acompañamos → implementamos → medimos y ajustamos.",
        services_business_step_1: "Diagnosticamos",
        services_business_step_2: "Priorizamos",
        services_business_step_3: "Acompañamos",
        services_business_step_4: "Implementamos",
        services_business_step_5: "Medimos y ajustamos",
        services_business_objective: "<strong>El objetivo:</strong> empresas con mejores capacidades para decidir, gestionar, financiarse, crecer y sostenerse.",
        services_business_card1_title: "Acceso a capital y mercados",
        services_business_card1_desc: "Conectamos capacidades productivas y empresariales con financiación, activos, clientes, proveedores, canales comerciales, encadenamientos y nuevos mercados, fortaleciendo las condiciones para crecer.",
        services_business_card2_title: "Género y enfoque diferencial",
        services_business_card2_desc: "Diseñamos soluciones que reconocen las barreras y oportunidades asociadas al género, cuidado, territorio, edad, pertenencia étnica, discapacidad y otras condiciones, incorporándolas desde el diseño hasta la evaluación.",
        services_business_card3_title: "Fortalecimiento organizacional",
        services_business_card3_desc: "Impulsamos capacidades de gestión, gobernanza, planificación, articulación, sostenibilidad y toma de decisiones de asociaciones, organizaciones e instituciones.",
        services_business_card4_title: "Investigación, innovación y evaluación",
        services_business_card4_desc: "Generamos evidencia mediante diagnósticos, segmentación, análisis de datos, pilotos, monitoreo y evaluación para comprender qué funciona, para quién, en qué contextos y bajo qué condiciones.",
        services_technology_title: "Tecnología, datos e IA para la inclusión",
        services_technology_desc: "Integramos herramientas digitales, analítica de datos e inteligencia artificial para ampliar el acceso al conocimiento, personalizar rutas de acompañamiento, facilitar la gestión y desarrollar soluciones escalables adaptadas a diferentes personas, empresas y contextos.",
        services_audience_title: "Diseñamos para diferentes personas y territorios",
        services_audience_desc_1: "Nuestra experiencia nos permite adaptar estas soluciones a mujeres, jóvenes, población rural, comunidades étnicas, víctimas del conflicto, personas 50+, emprendedores, mipymes, asociaciones productivas, organizaciones comunitarias e instituciones financieras y de desarrollo.",
        services_audience_desc_2: "Trabajamos desde el territorio, pero diseñamos soluciones con capacidad de adaptación, escalamiento y medición de resultados.",
        services_youth_eyebrow: "¿Qué hacemos?",
        services_youth_title: "Desarrollo de capacidades para niñez, adolescencia y juventud",
        services_youth_desc: "Diseñamos estrategias, programas e investigaciones que fortalecen las capacidades de niñas, niños, adolescentes y jóvenes para ampliar sus oportunidades educativas, laborales, sociales y comunitarias. Trabajamos con enfoque de derechos, diferencial y territorial, promoviendo participación significativa y soluciones adaptadas a las realidades y trayectorias de cada población.",
        services_business_lines_title: "Líneas de negocio",
        services_youth_card1_title: "Proyectos de vida y desarrollo de capacidades",
        services_youth_card1_desc: "Fortalecemos habilidades socioemocionales, personales y de liderazgo para impulsar la autonomía, la toma de decisiones y la construcción de proyectos de vida.",
        services_youth_card2_title: "Educación, empleabilidad y emprendimiento",
        services_youth_card2_desc: "Diseñamos rutas que conectan formación, habilidades y oportunidades de empleo, emprendimiento y generación de ingresos.",
        services_youth_card3_title: "Participación, ciudadanía y derechos",
        services_youth_card3_desc: "Desarrollamos metodologías para fortalecer el ejercicio de derechos, la participación significativa, el liderazgo y la incidencia de niñas, niños, adolescentes y jóvenes.",
        services_youth_card4_title: "Investigación y migración juvenil",
        services_youth_card4_desc: "Generamos evidencia para la toma de decisiones sobre las trayectorias juveniles, sus barreras y oportunidades, incluyendo educación, trabajo, permanencia y migración.",
        services_success_title: "Experiencias de éxito",
        services_success_card1_title: "Save the Children",
        services_success_card1_desc: "Investigación para comprender el ejercicio de derechos y fortalecer entornos protectores de niñas, niños y adolescentes, integrando evidencia cuantitativa y cualitativa desde las personas, las familias, las comunidades, las instituciones educativas, las organizaciones sociales y las autoridades locales.",
        services_success_card2_title: "Migración juvenil en Montes de María | 2026",
        services_success_card2_desc: "Investigación sobre los factores que inciden en las decisiones de permanencia y migración de jóvenes, orientada a generar evidencia para políticas y estrategias de desarrollo territorial.",
        services_success_card3_title: "Jornada Nacional de Limpieza del Lago de Tota | 2023",
        services_success_card3_desc: "Educación ambiental y participación ciudadana con niñas, niños, adolescentes, jóvenes y comunidades para fortalecer la conservación y apropiación del territorio.",
        services_success_card4_title: "Mis Derechos Sí Cuentan | 2017",
        services_success_card4_desc: "Fortalecimiento del conocimiento, ejercicio y protección de los derechos de niñas, niños y adolescentes mediante formación, participación comunitaria y articulación institucional.",
        services_care_title: "Diseño e implementación de Modelos Holísticos y Sostenibles de Cuidado, Salud y Bienestar",
        services_care_desc: "Diseñamos soluciones orientadas a fortalecer la <strong>capacidad funcional, el bienestar, la autonomía y la calidad de vida de las personas</strong> desde una perspectiva de longevidad saludable, nueva longevidad, prevención de la cronicidad, manejo de la multimorbilidad, nuevos modelos de cuidado y comunidades cuidadoras.",
        services_care_business_lines_title: "Líneas de negocio",
        services_care_card1_title: "Modelos de cuidado de largo plazo: Cuidar para Vivir Mejor",
        services_care_card1_desc: "Diseñamos modelos integrales de cuidado que fortalecen la autonomía, la capacidad funcional y la calidad de vida, articulando servicios, redes de apoyo, cuidadores y entornos.",
        services_care_card2_title: "Modelos y programas de longevidad saludable y con propósito",
        services_care_card2_desc: "Desarrollamos estrategias para promover un envejecimiento saludable y una nueva longevidad, con énfasis en prevención, bienestar, autonomía, participación y proyectos de vida.",
        services_care_card3_title: "Modelos de corresponsabilidad del cuidado: Cuidar entre Todos",
        services_care_card3_desc: "Diseñamos comunidades y sistemas de cuidado corresponsables que distribuyen las responsabilidades entre personas, familias, organizaciones, Estado y territorios.",
        services_care_card4_title: "Vivir Mejor con Condiciones de Larga Duración: Longevidad, cronicidad y multimorbilidad",
        services_care_card4_desc: "Diseñamos programas para prevenir la cronicidad y fortalecer el manejo integral de condiciones de larga duración y multimorbilidad, promoviendo funcionalidad, autonomía y bienestar.",
        services_care_card5_title: "Servicios y programas sociales para la longevidad: Bienestar a lo Largo de la Vida",
        services_care_card5_desc: "Diseñamos e implementamos servicios, programas e intervenciones sociales que responden a las necesidades de las personas a lo largo del proceso de envejecimiento, fortaleciendo inclusión, participación y calidad de vida.",
        services_silver_economy_title: "Economía Plateada y nuevas oportunidades",
        services_silver_economy_desc: "Diseñamos soluciones de <strong>emprendimiento 50+, empleabilidad senior, segunda carrera, mentoría e innovación</strong>, reconociendo la experiencia, capacidades y aspiraciones de las personas en diferentes momentos de su trayectoria laboral y productiva.",
        services_longevity_finance_title: "Finanzas para la Longevidad",
        services_longevity_finance_desc: "Diseñamos estrategias de <strong>ahorro, inclusión y protección financiera, educación previsional y preparación para el retiro</strong>, incorporando ciencias del comportamiento para comprender y facilitar decisiones financieras a lo largo de la vida.",
        services_success_title: "Experiencias de éxito",
        services_success_impact_title: "IMPACTO 50+",
        services_success_impact_partner: "MATE + KOGNITIVO + ZELVA",
        services_success_impact_desc: "A través de la Unión Temporal IMPACTO 50+, integrada por MATE SAS, KOGNITIVO SAS y ZELVA SAS, acompañaremos a entidades financieras para comprender mejor las necesidades, comportamientos y oportunidades de las personas 50+ y convertir ese conocimiento en nuevas soluciones.",
        services_success_conversation_title: "MATE en la conversación sobre longevidad y protección social",
        services_success_conversation_desc: "Participamos en espacios de conocimiento y articulación sobre <strong>economía de la longevidad, finanzas plateadas y los desafíos de vivir más años</strong>.",
        services_success_link_1: "Economía de la longevidad",
        services_success_link_2: "Pensiones y protección social",
        services_success_link_3: "Informalidad y vejez sin pensión",
        services_success_video_link: "Entrevista Noticias Caracol",
        services_longevity_team_title: "Nuestro equipo",
        services_longevity_team_desc: "Integramos conocimiento especializado en geriatría, salud pública, cuidado, bienestar, economía de la longevidad, inclusión financiera e innovación haciendo posible una mirada interdisciplinaria y técnica sobre la longevidad.",
        services_longevity_team_flip: "Girar",
        services_longevity_team_1_name: "Dr. Róbinson Cuadros Cuadros, MD",
        services_longevity_team_1_role: "Líder de Longevidad Saludable",
        services_longevity_team_1_bio: "Médico geriatra de la Universidad Nacional de Colombia, con más de 15 años de experiencia en el diseño de políticas públicas, programas y proyectos de longevidad saludable. Expresidente de la Asociación Colombiana de Gerontología y Geriatría y actual presidente del COMLAT.",
        services_longevity_team_2_name: "Wilson Daniel Ossa Pérez, MPH",
        services_longevity_team_2_role: "Líder de Cuidado para una Nueva Longevidad",
        services_longevity_team_2_bio: "Filósofo, psicólogo y máster en Salud Pública. Experto en modelos integrales de cuidado, protección social e innovación social para la longevidad saludable. Cofundador de Lazos Humanos, hoy Versania Cuidado y Vida.",
        services_longevity_team_3_name: "Marisol Acosta",
        services_longevity_team_3_role: "Líder de Bienestar Holístico",
        services_longevity_team_3_bio: "Ingeniera Industrial, especialista en Gerencia del Talento Humano, con 24 años de experiencia directiva en los sectores financiero, educativo, público y de servicios. Cofundadora de ANDEL.",
        services_longevity_cta_title: "Una sociedad que vive más necesita soluciones para toda la vida",
        services_longevity_cta_desc: "Comprender el curso de vida nos permite anticipar necesidades, fortalecer capacidades y diseñar mejores oportunidades para el presente y el futuro.",
        services_longevity_cta_button: "Hablemos de longevidad",
        services_capabilities_title: "Capacidades que potencian nuestras soluciones",
        services_capabilities_desc: "Ponemos capacidades transversales al servicio de cada proyecto para diseñar, implementar, medir y escalar soluciones.",
        services_capability_1_title: "Innovación y desarrollo",
        services_capability_1_desc: "Diseñamos ecosistemas, modelos y alianzas que conectan actores, fortalecen organizaciones y convierten oportunidades en soluciones sostenibles.",
        services_capability_1_tags: "Innovación social · Ecosistemas · Desarrollo de negocios · Gobernanza · Articulación",
        services_capability_2_title: "Investigación, datos y comportamiento",
        services_capability_2_desc: "Generamos evidencia para comprender personas y territorios, orientar decisiones y mejorar resultados.",
        services_capability_2_tags: "Investigación · Analítica de datos · MEL · Ciencias del comportamiento · Evaluación",
        services_capability_3_title: "Sostenibilidad e impacto",
        services_capability_3_desc: "Integramos las dimensiones económica, social y ambiental para generar valor sostenible y resultados medibles.",
        services_capability_3_tags: "Sostenibilidad · Cadenas de valor · Economía circular · Impacto · Desarrollo territorial",
        services_capability_4_title: "Capacidad operativa",
        services_capability_4_desc: "Complementamos nuestras intervenciones con la gestión de bienes, equipos, dotaciones, tecnología y logística cuando los proyectos lo requieren.",
        services_capability_4_tags: "Suministro · Dotaciones · Tecnología · Logística · Soporte",
        hero_btn_1: "Conoce nuestras soluciones",
        hero_btn_2: "Hablemos de una alianza",

        // 1.2 Quiénes Somos (Home)
        home_about_headline: "Somos <span class='text-primary'>MATE</span>, una firma con experiencia en Colombia y América Latina que acompaña la inclusión económica con enfoque territorial, social y diferencial.",
        home_about_subtext: "Trabajamos con entidades públicas, privadas, de cooperación y organizaciones territoriales para diseñar e implementar soluciones que fortalecen capacidades, promueven autonomía económica y conectan a las personas con más y mejores oportunidades.",
        home_about_btn: "Conocernos",

        // 1.3 Diferencia (Home)
        home_diff_title: "¿Por qué somos diferentes?",
        home_diff_subtitle: "Construimos rutas integrales que conectan personas, capacidades, servicios, datos y alianzas para generar cambios sostenibles.",
        home_diff_card1_title: "Apasionamiento con propósito",
        home_diff_card1_desc: "En MATE compartimos una gran pasión por lo que hacemos y la direccionamos hacia un mismo propósito: hacer que las personas no solo vivan MÁS sino que vivan en las MEJORES condiciones de salud, económicas, de bienestar y calidad de vida.",
        home_diff_card2_title: "Propósito con dirección",
        home_diff_card2_desc: "Para alcanzar el propósito nos apalancamos en metodologías, enfoques y técnicas serias, probadas y científicas que nos permiten mantener el rumbo en tanto cimentamos nuestra acción en la mejor evidencia posible.",
        home_diff_card3_title: "Resultados con rostro social",
        home_diff_card3_desc: "Además de los resultados, medidos con indicadores técnicos, nos interesa medir los impactos, lo que nos lleva a visibilizar las transformaciones que acontecen en el tejido social.",
        home_diff_card4_title: "Calidad con calidez",
        home_diff_card4_desc: "El valor superior siempre serán las personas y por ello nuestra atención siempre estará centrada en ellas respetando sus diferencias y las características de cada contexto y territorio que habitan.",

        // 1.4 Iniciativas (Home)
        home_init_title: "Iniciativas que hoy marcan nuestra agenda",
        // Títulos de pestañas
        init_tab_b: "Modelo Étnico",
        init_tab_c: "Fundación MATE",
        init_tab_e: "Gobierno Corporativo",
        // Contenidos
        init_content_b: "Una apuesta que integra asociatividad, fortalecimiento productivo, identidad cultural y canales de comercialización.",
        init_content_c: "Una iniciativa para movilizar alianzas, filantropía y cofinanciación alrededor de la inclusión económica y la ciudadanía inclusiva.",
        init_content_e: "Una línea orientada a acompañar a las organizaciones, no importa su tamaño, en el fortalecimiento de su gobierno corporativo, promoviendo estructuras de dirección más sólidas, transparentes y orientadas a la sostenibilidad.",
        init_btn: "Ver soluciones",

        // 1.5 Qué Hacemos (Home)
        home_do_title: "¿Cómo lo hacemos?",
        home_do_subtitle: "La experiencia nos enseñó que las personas parten de distintos lugares y cada territorio ofrece diferentes oportunidades. Por ello, en MATE primero COMPRENDEMOS y luego ACTUAMOS.",

        home_do_card1_title: "Enfoque territorial y diferencial",
        home_do_card1_desc: "Partimos de las personas y de las oportunidades del territorio para adaptar cada intervención a diferentes realidades, capacidades y necesidades.",

        home_do_card2_title: "Mirada integral",
        home_do_card2_desc: "Generamos visiones integrales e integradas por medio de la configuración de equipos interdisciplinarios de trabajo compuestos por profesionales con amplia experiencia y actitud empática.",

        home_do_card3_title: "Trabajo colaborativo",
        home_do_card3_desc: "Articulamos sector público, cooperación, empresas, comunidades y ecosistemas emprendedores desde una visión de inter y trans sectorialidad.",

        home_do_card4_title: "Decisiones con evidencia",
        home_do_card4_desc: "Incorporamos diagnóstico, seguimiento, analítica de datos, ciencias del comportamiento y ciencias de la implementación para comprender mejor y orientar la toma de decisiones en la ejecución.",

        home_do_card5_title: "Impacto con propósito",
        home_do_card5_desc: "Buscamos resultados que fortalezcan el bienestar, la autonomía y las oportunidades reales, buscando que cada etapa del curso de vida sea un paso firme hacia una nueva longevidad.",

        home_do_btn: "Ver todas las soluciones",

        // 1.6 Experiencia e Impacto (Home)
        exp_title: "Experiencia e impacto",
        exp_big_num: "+1'000.000",
        exp_big_label: "personas impactadas en Colombia",
        exp_btn: "Conoce más",
        exp_desc: "Nuestra experiencia combina trabajo en territorio, fortalecimiento de capacidades, inclusión financiera, investigación aplicada y articulación institucional.",
        exp_stat1_num: "+500",
        exp_stat1_label: "emprendimientos",
        exp_stat2_num: "+100",
        exp_stat2_label: "comunidades",
        exp_stat3_num: "+50",
        exp_stat3_label: "alianzas",

        // Footer
        footer_desc: "Impulsamos inclusión económica y ciudadanía inclusiva a través de soluciones productivas, financieras, sociales y sostenibles.",
        footer_links_title: "Enlaces",
        footer_contact_title: "Contacto",
        footer_location_1: "Bogotá D.C.",
        footer_location_2: "Montería, Córdoba",
        footer_location_3: "Colombia, Sur América",
        footer_rights: "© 2026 MATE Inversiones & Negocios SAS. Todos los derechos reservados.",
        developed_by: "Desarrollado por",

        // --- PÁGINA: SOMOS MATE ---

        // Hero Section ---
        hero_about_title: "Somos MATE",
        hero_about_desc: "Más de 10 años impulsando inclusión económica, financiera y social en Colombia y América Latina.",

        // --- Acerca de la empresa y Misión ---
        history_title: "Nuestra Historia",
        history_text_1: "Hace 10 años, sobre una experiencia de más de 23 años transformando políticas y programas sociales en Colombia y América Latina, nació MATE. Aprendimos y seguimos aprendiendo en el territorio, trabajando junto a personas, comunidades, organizaciones e instituciones entendiendo sus realidades, capacidades y barreras. Esta experiencia nos enseña que existen soluciones DIVERSAS: cada territorio, cada comunidad y cada persona requiere respuestas pertinentes y diferenciales. Por eso diseñamos e implementamos soluciones que conectan capacidades, actores y oportunidades, y que se pueden adaptar y escalar.",
        history_text_2: "Hoy sumamos la analítica de datos, las ciencias del comportamiento y de la implementación a la visión de longevidad saludable y nueva longevidad confiando que, con el soporte y la potencia de las tecnologías de la información, seamos más asertivos a la hora de saber qué funciona, para quiénes y en qué condiciones.",
        history_text_3: "Así convertimos experiencia y evidencia en soluciones que generan oportunidades, transforman realidades y hacen posible un mayor impacto.",
        about_company_title: "Acerca de la organización",
        about_company_subtitle: "¿Quiénes somos?",
        about_company_text: "Somos <strong>MATE</strong>, una firma consultora colombiana que impulsa la transformación social desde la innovación. Convertimos <strong>capacidades en oportunidades y oportunidades en mejores condiciones de vida</strong>, conectando personas, organizaciones y territorios para generar cambios que perduran. Diseñamos e implementamos soluciones que combinan <strong>conocimiento del territorio, evidencia, experiencia, innovación y tecnología</strong> para responder a desafíos sociales complejos y convertirlos en oportunidades de desarrollo.",
        mission_title: "Nuestra Misión",
        mission_text: "Transformamos desafíos sociales y económicos en oportunidades de desarrollo y realización mediante el diseño e implementación de soluciones que fortalecen capacidades, conectan personas, organizaciones y territorios, y generan mejores condiciones a lo largo del curso de vida.",

        // --- Cómo trabajamos ---
        how_title: "Cómo trabajamos",
        how_c1_title: "Escuchamos y comprendemos",
        how_c1_desc: "Escuchamos a las comunidades, entendemos sus necesidades, analizamos el territorio y su contexto para identificar las capacidades, brechas y oportunidades.",
        how_c2_title: "Diseñamos rutas de acción",
        how_c2_desc: "Construimos de manera conjunta propuestas ajustadas al contexto, a las personas y a los objetivos de cada alianza.  ",
        how_c3_title: "Implementamos y acompañamos",
        how_c3_desc: "Desarrollamos procesos con cercanía territorial, formación, asistencia técnica y articulación.",
        how_c4_title: "Medimos y aprendemos",
        how_c4_desc: "Hacemos seguimiento, recogemos aprendizajes y ajustamos para mejorar resultados.",

        team_title: "Nuestro Equipo",
        team_subtitle: "Conoce a las personas que impulsan la visión estratégica y el impacto de MATE SAS.",

        // --- Hitos Institucionales ---        
        hitos_title: "Hitos Institucionales",
        recognition_badge: "Reconocimiento Internacional",
        recognition_text: "MATE recibió el reconocimiento a la Mejor práctica local con enfoque de género en el marco de la VII Cumbre Iberoamericana de Agendas Locales de Género y del XV Congreso Iberoamericano de Municipalistas, realizados en Zapopan, México, en 2025 como reflejo de su compromiso con la inclusión, la equidad y la transformación territorial.",

        // --- Nuestro equipo --- 
        // Equipo - P1
        team_p1_name: "Ana Milena Negrette",
        team_p1_role: "Fundadora y Directora General",
        team_p1_bio: "Lidera la visión estratégica de MATE y la consolidación de iniciativas que conectan territorio, inclusión y oportunidades. Tiene más de 22 años de experiencia en desarrollo rural, género, emprendimiento e inclusión económica, acompañando procesos y poblaciones vulnerables en Colombia y América Latina. Es Administradora de Empresas, Licenciada en Biología, Magíster en Desarrollo Rural y en Género, Especialista en Ecología, con estudios en desarrollo económico local, emprendimiento e inversión de impacto.",

        // Equipo - P2
        team_p2_name: "Any Andrea Benítez",
        team_p2_role: "Experta en inclusión financiera y protección social",
        team_p2_bio: "Experta en inclusión financiera y protección social. Tiene más de 22 años de experiencia en Colombia y América Latina, y una trayectoria destacada en educación financiera, ahorro, aseguramiento, ahorro para la vejez y economía plateada. Es Ingeniera Agroindustrial, MBA y Máster en Liderazgo Internacional, Especialista en Gobierno, Gerencia y Asuntos Públicos, con estudios en gobierno corporativo.",

        // Equipo - P3
        team_p3_name: "Ivonne Villada",
        team_p3_role: "Experta en Inclusión financiera, género y transformación digital",
        team_p3_bio: "Especialista en inclusión financiera y protección social, con más de 16 años de experiencia en América Latina. Ha liderado iniciativas de educación financiera, género y diversidad para ampliar oportunidades y acceso a servicios financieros en poblaciones vulnerables. Es Administradora Ambiental y Magíster en Desarrollo Rural, con estudios en Desarrollo Económico Local, investigación e impacto de políticas públicas de telecomunicaciones en América Latina.",

        // Equipo - P4
        team_p4_name: "Claudia Sofía Santacruz",
        team_p4_role: "Experta en proyectos",
        team_p4_bio: "Experta en planeación y ejecución de proyectos, coordinación de equipos multidisciplinarios y aplicación de sistemas Monitoreo Evaluación y Aprendizaje, gestión de riesgos y toma de decisiones basada en datos. Es Ingeniera Industrial, Especialista en Sistemas Gerenciales de Ingeniería con énfasis en Proyectos y Producción, con formación en International Project Management bajo lineamientos PMBOK.",

        // Equipo - P5
        team_p5_name: "Estefany Brieva",
        team_p5_role: "Líder Contable y de Gestión Financiera",
        team_p5_bio: "Líder de la gestión financiera y contable de los proyectos, contribuyendo a la solidez administrativa y al control de los procesos internos. Contadora Pública y Especialista en Gerencia de Proyectos.",

        // Equipo - P6
        team_p6_name: "Mauricio Romero Posada",
        team_p6_role: "Líder de Investigación, Monitoreo y Evaluación",
        team_p6_bio: "Antropólogo y Especialista en Gestión de Empresas del Sector Solidario, con experiencia en la coordinación de investigaciones y equipos multidisciplinarios en América Latina y África para la investigación social, el monitoreo y la evaluación de programas de desarrollo e inclusión económica y financiera. Experto en metodologías cualitativas y cuantitativas, investigación etnográfica y trabajo con poblaciones vulnerables y diversas.",

        // Equipo - P7
        team_p7_name: "José Carlos Zapa",
        team_p7_role: "Líder Territorial Nacional",
        team_p7_bio: "Administrador de Empresas, educador musical y Especialista en Gerencia de Proyectos, con experiencia en desarrollo empresarial, fortalecimiento organizacional e inclusión económica y financiera de proyectos productivos. Su trayectoria se basa en la gestión territorial y la implementación de proyectos en diversas regiones de Colombia.",

        // Equipo - P8
        team_p8_name: "Martha Rengifo",
        team_p8_role: "Líder Territorial Sur-Occidente",
        team_p8_bio: "Administradora de Empresas, Administradora Turística y Hotelera y Gestora de Mercados, con experiencia en dirección estratégica, desarrollo empresarial y territorial, gestión comercial y fortalecimiento de cadenas productivas, articulación institucional, acompañamiento a organizaciones y comunidades e inteligencia de mercados. Cuenta con enfoque diferencial y de desarrollo territorial.",

        // Equipo - P10
        team_p10_name: "Claudia Negrete Contreras",
        team_p10_role: "Líder Territorial Caribe",
        team_p10_bio: "Licenciada en Informática Educativa y Medios Audiovisuales y Especialista en Administración de la Informática Educativa, con experiencia en gestión territorial, educación, acompañamiento social y comunitario y coordinación de proyectos. Ha trabajado con niñas, niños, adolescentes, jóvenes, familias y comunidades, así como en levantamiento y seguimiento de información, gestión logística y administrativa y articulación con actores comunitarios, incorporando herramientas pedagógicas y tecnológicas en los procesos de intervención.",

        // Equipo - P11
        team_p11_name: "Erick Sebastián Bermúdez Rodríguez",
        team_p11_role: "Gestión de Procesos y Data",
        team_p11_bio: "Ingeniero Industrial y Especialista en Gerencia de Proyectos, con experiencia en planeación estratégica, seguimiento y control de proyectos y optimización de procesos organizacionales. Cuenta con experiencia en la estructuración simple de sistemas complejos, diseño de herramientas de seguimiento y evaluación, gestión de procesos de captura masiva de información y análisis de datos para la toma de decisiones, asegurando trazabilidad, calidad y oportunidad de la información.",

        // --- Alianzas ---
        alliances_title: "Soy porque SOMOS: el poder de las alianzas",
        alliances_text: "Construimos alianzas estratégicas con organizaciones que complementan nuestra experiencia y nos permiten integrar nuevas capacidades, metodologías y tecnologías para responder a desafíos cada vez más complejos.",
        alliances_card1_title: "UT FINCLUSIÓN",
        alliances_card1_partner: "MATE + INSTINTIVO",
        alliances_card1_desc: "Inclusión financiera, ciencias del comportamiento e innovación.",
        alliances_visit_instintivo: "Conoce a Instintivo",
        alliances_card2_title: "UT IMPACTO 50+",
        alliances_card2_partner: "MATE + INSTINTIVO + ZELVA",
        alliances_card2_desc: "Longevidad, finanzas plateadas, ciencias del comportamiento, experiencia de usuario y comunicación.",
        alliances_instintivo_link: "Conoce a Instintivo",
        alliances_zelva_link: "Conoce a Zelva",
        alliances_card3_title: "PropulXora",
        alliances_card3_partner: "MATE + PROPULSOR LATINOAMÉRICA",
        alliances_card3_desc: "Alianza entre MATE y Propulsor Latinoamérica para fortalecer empresas mediante tecnología, inteligencia empresarial, innovación y acceso a financiamiento.",
        alliances_propulsor_link: "Conoce a Propulsor",
        alliances_card4_title: "Fondo Mujer",
        alliances_card4_desc: "Participación como aliados técnicos y conferencistas en procesos de fortalecimiento del emprendimiento femenino.",
        alliances_fondo_mujer_link_1: "Ver conferencia de Mujeres Microempresarias: Retos y barreras",
        alliances_fondo_mujer_link_2: "Ver conferencia de Ahorro y longevidad: hacia una vejez con autonomía y bienestar",
        alliances_card5_title: "ANDEL",
        alliances_card5_desc: "MATE hace parte de la Asociación Nacional de Agencias de Desarrollo Local (ANDEL), una red que promueve el desarrollo económico territorial mediante la articulación entre gobiernos, empresas, academia y organizaciones sociales.",
        alliances_card5_note: "Participación en las discusiones nacionales sobre economía de la longevidad.",
        alliances_card6_title: "Gobierno Corporativo",
        alliances_card6_desc: "MATE participa activamente en la construcción de mejores prácticas de gobernanza empresarial.",
        alliances_card6_item1: "Participación institucional",
        alliances_card6_item2: "Miembros de la Junta Directiva del Grupo de Estudio de Gobierno Corporativo de Uniandinos.",
        alliances_card6_item3: "Diseño e implementación de modelos de gobernanza para empresas, organizaciones sociales y alianzas público-privadas.",
        alliances_card6_item4: "Redes de liderazgo.",
        alliances_quote: "\"Las alianzas adecuadas convierten una intención en una transformación sostenible.\"",

        // --- PÁGINA: PROYECTOS ---
        // --- Hero Section ---
        hero_proj_title: "Experiencia que se traduce en acción",
        hero_proj_desc: "Nuestra experiencia combina trabajo en territorio, fortalecimiento de capacidades, inclusión financiera, investigación aplicada y articulación institucional.",

        // Detalle de Servicios/Proyectos
        serv_muelle_title: "Muelle Turístico de Buenaventura (2017–2023)",
        serv_muelle_desc: "Diseño e implementación del plan de concesión, integrando modernización operativa y acompañamiento social. Estructuración de la articulación con actores clave y fortalecimiento de la gestión estratégica, procesos y riesgos. Desarrollo de estrategias de experiencia de usuario, educación financiera y acceso a productos financieros para la comunidad del muelle.",

        serv_a_title: "Mujer Étnica",
        serv_a_desc: "Una metodología desarrollada por MATE para fortalecer emprendimientos de mujeres de comunidades étnicas, integrando identidad cultural, desarrollo empresarial, inclusión financiera, activos productivos y acceso a mercados.",
        serv_a_flow_1: "Comprender",
        serv_a_flow_2: "Fortalecer",
        serv_a_flow_3: "Impulsar",
        serv_a_flow_4: "Conectar",
        serv_a_flow_5: "Consolidar",

        serv_b_title: "Banca de las Oportunidades",
        serv_b_desc: "Elaboramos recomendaciones estratégicas para el diseño de programas de ahorro dirigidos a poblaciones de bajos ingresos y/o vulnerables.",

        serv_c_title: "Migración juvenil rural",
        serv_c_desc: "Lideramos una investigación sobre los factores que inciden en la migración de jóvenes rurales, generando insumos para decisiones y políticas con enfoque territorial.",

        serv_d_title: "Familias en su Tierra",
        serv_d_desc: "Acompañamos procesos de retorno de hogares víctima del conflicto con acciones en seguridad alimentaria, vivienda y generación de ingresos.",

        serv_e_title: "Alianza Bancalimentos",
        serv_e_desc: "Desarrollamos y adaptamos productos financieros incluyentes para población vulnerable, articulando canales, incentivos, comunicación y validación en territorio.",

        serv_f_title: "Educación financiera digital para mujeres en Chile",
        serv_f_desc: "Diseñamos y adaptamos un producto digital de educación financiera para mujeres en condición de vulnerabilidad, con enfoque pedagógico y conductual.",

        cta_capitaliza_title: "Capitaliza tu negocio",
        cta_capitaliza_text: "Te ayudamos a valorar tu emprendimiento y a explorar opciones de financiamiento.",

        // --- PÁGINA: CONTACTO ---
        hero_contact_title: "Hablemos de su próximo proyecto",
        hero_contact_desc: "Estamos listos para escuchar sus necesidades y construir juntos soluciones con impacto territorial y social.",
        contact_info_title: "Información de Contacto",
        contact_info_desc: "Completa el formulario y nuestro equipo se pondrá en contacto contigo",
        contact_write_us: "Escríbenos",
        contact_call_us: "WhatsApp",
        contact_location_label: "Ubicación",
        contact_follow_us: "Síguenos",

        // Formulario
        form_name: "Nombre completo",
        form_name_placeholder: "Tu nombre",
        form_entity: "Empresa / Entidad",
        form_entity_placeholder: "Nombre de tu organización",
        form_email: "Correo electrónico",
        form_email_placeholder: "tucorreo@ejemplo.com",
        form_phone: "Teléfono de contacto",
        form_phone_placeholder: "Ej: +57 300 123 4567",
        form_subject: "Asunto",
        opt_alliance: "Propuesta de Alianza",
        opt_consulting: "Consultoría / Servicios",
        opt_info: "Solicitud de Información",
        opt_other: "Otro",
        form_message: "Mensaje",
        form_message_placeholder: "Cuéntanos más sobre cómo podemos ayudarte...",
        form_privacy_text: "Acepto la",
        form_privacy_link: "Política de Tratamiento de Datos Personales",
        form_btn: "Enviar Mensaje",
        form_sending: "Enviando...",
        form_success: "Gracias. Tu mensaje fue enviado para procesamiento. Nos comunicaremos contigo pronto.",
        form_error: "No fue posible enviar el mensaje. Por favor, verifica tu conexión e intenta de nuevo más tarde.",

        // Validación de seguridad (Captcha)
        captcha_label: "Validación de seguridad: ¿Cuánto es ",
        captcha_placeholder: "Tu respuesta",
        captcha_error: "La respuesta de seguridad es incorrecta.",

        contact_follow_us: "Síguenos",
        social_instagram: "Instagram",
        social_linkedin: "LinkedIn",

    },
    en: {
        // Navegación
        nav_home: "Home",
        nav_about: "We're MATE",
        nav_projects: "Experience",
        nav_services: "Services",
        nav_contact: "Contact Us",
        submenu_about_top: "Top",
        submenu_about_history: "Our History",
        submenu_about_mission: "Mission & Vision",
        submenu_about_milestones: "Institutional Milestones",
        submenu_about_team: "Our Team",
        submenu_about_work: "How we work",
        submenu_about_alliances: "Alliances",
        submenu_services_longevity: "Longevity, Well-Being and Care",
        submenu_services_economic: "Economic Inclusion and Financial Autonomy",

        // --- PÁGINA: INDEX (HOME) ---
        // SEO (Inicio)
        meta_title_index: "MATE | Investments & Business",
        meta_desc_index: "We drive economic inclusion and inclusive citizenship through productive, financial, social, and sustainable solutions.",
        meta_title_experiencia: "Experience | MATE Investments & Business",
        meta_desc_experiencia: "Learn about MATE’s experience and solutions in productive and financial inclusion, social strengthening, and sustainability.",
        meta_title_servicios: "Services | MATE Investments & Business",
        meta_desc_servicios: "Learn about MATE’s services in longevity, well-being, care, economic inclusion, and financial autonomy.",
        // 1.1 Hero Section        
        hero_badge_text: "Social Transformation",
        hero_title: "More capabilities.<br />More opportunities.<br />More well-being.",
        hero_subtitle: "At MATE, we connect territories, people, and stakeholders to advance opportunities, transform realities hand in hand with communities, and foster well-being throughout life.",
        services_hero_title: "Services",
        services_hero_desc: "We design solutions that transform capacities into opportunities and opportunities into well-being.",
        services_section_label: "MATE Services",
        services_longevity_title: "Longevity, Well-Being and Care",
        services_longevity_text: "At MATE, we understand longevity from a life-course perspective. We therefore support people at every stage, strengthening their capacities, well-being, autonomy, and participation so they can live better, for longer, and with greater opportunities. To do so, we design solutions that connect <strong>well-being, care, autonomy, and protection</strong> from childhood and youth through the most advanced stages of life.",
        services_economic_title: "Economic Inclusion and Financial Autonomy",
        services_economic_text_1: "We design and implement solutions that enable people, households, entrepreneurs, businesses, and organizations to strengthen their capacities, generate income, make better decisions, and access economic and financial opportunities sustainably.",
        services_economic_text_2: "We integrate financial inclusion, business development, market access, technology, data, and behavioral sciences, tailoring every solution to the capacities, barriers, and opportunities of people and territories.",
        services_economic_what_we_do: "What do we do?",
        services_economic_card1_title: "Financial Inclusion",
        services_economic_card1_desc: "We design solutions that expand access to, use of, and effective uptake of <strong>savings, credit, insurance, payments, investment, and other financial services</strong>, connecting them with the real needs and capacities of people and businesses.",
        services_economic_card2_title: "Financial Education and Capabilities",
        services_economic_card2_desc: "We develop in-person, digital, and hybrid methodologies to strengthen knowledge, behaviors, and decisions related to <strong>income, savings, credit, debt, protection, investment, and financial well-being</strong>.",
        services_economic_card3_title: "Economic Autonomy and Income Generation",
        services_economic_card3_desc: "We design pathways that strengthen capacities, income, productive assets, and economic autonomy, especially for populations facing greater barriers to accessing opportunities.",
        services_business_label: "MATE BUSINESS",
        services_business_title: "Business Development and Strengthening",
        services_business_intro_1: "Our business support model begins with a premise: <strong>every business has different capabilities, challenges, and opportunities; therefore, not all need the same pathway.</strong>",
        services_business_intro_2: "Through the Business Capability Index, we assess each business comprehensively, identify strengths and gaps, and build a tailored strengthening pathway.",
        services_business_model_desc: "We integrate ongoing financial recordkeeping, modular technical assistance, training, management tools, mentoring and advisory boards, behavioral sciences, and connections to networks and markets, supporting businesses from diagnosis through implementation and results measurement.",
        services_business_process: "We diagnose → prioritize → support → implement → measure and adjust.",
        services_business_step_1: "We diagnose",
        services_business_step_2: "We prioritize",
        services_business_step_3: "We support",
        services_business_step_4: "We implement",
        services_business_step_5: "We measure<br>and adjust",
        services_business_objective: "<strong>The objective:</strong> businesses with stronger capacities to make decisions, manage, secure financing, grow, and sustain themselves.",
        services_business_card1_title: "Access to Capital and Markets",
        services_business_card1_desc: "We connect productive and business capabilities with financing, assets, customers, suppliers, sales channels, value chains, and new markets, strengthening the conditions for growth.",
        services_business_card2_title: "Gender and Differentiated Approach",
        services_business_card2_desc: "We design solutions that recognize barriers and opportunities associated with gender, care, territory, age, ethnic background, disability, and other conditions, incorporating them from design through evaluation.",
        services_business_card3_title: "Organizational Strengthening",
        services_business_card3_desc: "We strengthen the management, governance, planning, coordination, sustainability, and decision-making capacities of associations, organizations, and institutions.",
        services_business_card4_title: "Research, Innovation, and Evaluation",
        services_business_card4_desc: "We generate evidence through assessments, segmentation, data analysis, pilots, monitoring, and evaluation to understand what works, for whom, in which contexts, and under what conditions.",
        services_technology_title: "Technology, Data, and AI for Inclusion",
        services_technology_desc: "We integrate digital tools, data analytics, and artificial intelligence to expand access to knowledge, personalize support pathways, facilitate management, and develop scalable solutions tailored to different people, businesses, and contexts.",
        services_audience_title: "We Design for Different People and Territories",
        services_audience_desc_1: "Our experience enables us to tailor these solutions to women, young people, rural populations, ethnic communities, victims of conflict, people aged 50+, entrepreneurs, micro, small, and medium-sized enterprises, producer associations, community organizations, and financial and development institutions.",
        services_audience_desc_2: "We work from the territory while designing solutions with the capacity to adapt, scale, and measure results.",
        services_youth_eyebrow: "What do we do?",
        services_youth_title: "Capacity Development for Children, Adolescents, and Youth",
        services_youth_desc: "We design strategies, programs, and research that strengthen the capacities of children, adolescents, and young people to expand their educational, employment, social, and community opportunities. We work from a rights-based, differentiated, and territorial approach, promoting meaningful participation and solutions tailored to the realities and life trajectories of each population.",
        services_business_lines_title: "Business Lines",
        services_youth_card1_title: "Life Projects and Capacity Development",
        services_youth_card1_desc: "We strengthen socioemotional, personal, and leadership skills to foster autonomy, decision-making, and the development of life projects.",
        services_youth_card2_title: "Education, Employability, and Entrepreneurship",
        services_youth_card2_desc: "We design pathways that connect training, skills, and opportunities for employment, entrepreneurship, and income generation.",
        services_youth_card3_title: "Participation, Citizenship, and Rights",
        services_youth_card3_desc: "We develop methodologies to strengthen the exercise of rights, meaningful participation, leadership, and the influence of children, adolescents, and young people.",
        services_youth_card4_title: "Research and Youth Migration",
        services_youth_card4_desc: "We generate evidence for decision-making on young people’s life trajectories, barriers, and opportunities, including education, work, staying, and migration.",
        services_success_title: "Success Stories",
        services_success_card1_title: "Save the Children",
        services_success_card1_desc: "Research to understand the exercise of rights and strengthen protective environments for children and adolescents, integrating quantitative and qualitative evidence from individuals, families, communities, educational institutions, social organizations, and local authorities.",
        services_success_card2_title: "Youth Migration in Montes de María | 2026",
        services_success_card2_desc: "Research on the factors influencing young people’s decisions to stay or migrate, aimed at generating evidence for territorial development policies and strategies.",
        services_success_card3_title: "National Lake Tota Cleanup Day | 2023",
        services_success_card3_desc: "Environmental education and citizen participation with children, adolescents, young people, and communities to strengthen conservation and connection with the territory.",
        services_success_card4_title: "My Rights Count | 2017",
        services_success_card4_desc: "Strengthening the knowledge, exercise, and protection of children’s and adolescents’ rights through training, community participation, and institutional coordination.",
        services_care_title: "Design and Implementation of Holistic and Sustainable Care, Health, and Well-Being Models",
        services_care_desc: "We design solutions aimed at strengthening people’s <strong>functional capacity, well-being, autonomy, and quality of life</strong> from a perspective of healthy longevity, new longevity, prevention of chronic conditions, multimorbidity management, new care models, and caring communities.",
        services_care_business_lines_title: "Business Lines",
        services_care_card1_title: "Long-Term Care Models: Caring to Live Better",
        services_care_card1_desc: "We design comprehensive care models that strengthen autonomy, functional capacity, and quality of life by integrating services, support networks, caregivers, and environments.",
        services_care_card2_title: "Healthy, Purposeful Longevity Models and Programs",
        services_care_card2_desc: "We develop strategies to promote healthy aging and new longevity, with an emphasis on prevention, well-being, autonomy, participation, and life projects.",
        services_care_card3_title: "Shared-Responsibility Care Models: Caring Together",
        services_care_card3_desc: "We design communities and shared-responsibility care systems that distribute responsibilities among people, families, organizations, the State, and territories.",
        services_care_card4_title: "Living Better with Long-Term Conditions: Longevity, Chronic Conditions, and Multimorbidity",
        services_care_card4_desc: "We design programs to prevent chronic conditions and strengthen the comprehensive management of long-term conditions and multimorbidity, promoting functionality, autonomy, and well-being.",
        services_care_card5_title: "Social Services and Programs for Longevity: Well-Being Throughout Life",
        services_care_card5_desc: "We design and implement social services, programs, and interventions that respond to people’s needs throughout the aging process, strengthening inclusion, participation, and quality of life.",
        services_silver_economy_title: "Silver Economy and New Opportunities",
        services_silver_economy_desc: "We design solutions for <strong>50+ entrepreneurship, senior employment, second careers, mentoring, and innovation</strong>, recognizing people’s experience, capabilities, and aspirations at different points in their working and productive journeys.",
        services_longevity_finance_title: "Finance for Longevity",
        services_longevity_finance_desc: "We design strategies for <strong>savings, financial inclusion and protection, retirement education, and retirement preparedness</strong>, incorporating behavioral sciences to understand and facilitate financial decisions throughout life.",
        services_success_title: "Success stories",
        services_success_impact_title: "IMPACTO 50+",
        services_success_impact_partner: "MATE + KOGNITIVO + ZELVA",
        services_success_impact_desc: "Through the IMPACTO 50+ Temporary Partnership, formed by MATE SAS, KOGNITIVO SAS, and ZELVA SAS, we will support financial institutions in better understanding the needs, behaviors, and opportunities of people aged 50+ and turning that knowledge into new solutions.",
        services_success_conversation_title: "MATE in the Conversation on Longevity and Social Protection",
        services_success_conversation_desc: "We take part in knowledge-sharing and collaborative spaces on the <strong>longevity economy, silver finance, and the challenges of living longer</strong>.",
        services_success_link_1: "The longevity economy",
        services_success_link_2: "Pensions and social protection",
        services_success_link_3: "Informality and retirement without a pension",
        services_success_video_link: "Noticias Caracol Interview",
        services_longevity_team_title: "Our Team",
        services_longevity_team_desc: "We bring together specialist knowledge in geriatrics, public health, care, well-being, longevity economics, financial inclusion, and innovation, enabling an interdisciplinary and technical approach to longevity.",
        services_longevity_team_flip: "Flip",
        services_longevity_team_1_name: "Dr. Róbinson Cuadros Cuadros, MD",
        services_longevity_team_1_role: "Healthy Longevity Lead",
        services_longevity_team_1_bio: "Geriatric physician from the National University of Colombia, with more than 15 years of experience in designing public policies, programs, and projects for healthy longevity. Former President of the Colombian Association of Gerontology and Geriatrics and current President of COMLAT.",
        services_longevity_team_2_name: "Wilson Daniel Ossa Pérez, MPH",
        services_longevity_team_2_role: "Care Lead for a New Longevity",
        services_longevity_team_2_bio: "Philosopher, psychologist, and Master of Public Health. Expert in comprehensive care models, social protection, and social innovation for healthy longevity. Co-founder of Lazos Humanos, now Versania Cuidado y Vida.",
        services_longevity_team_3_name: "Marisol Acosta",
        services_longevity_team_3_role: "Holistic Well-being Lead",
        services_longevity_team_3_bio: "Industrial Engineer and Human Talent Management Specialist, with 24 years of leadership experience in the financial, education, public, and service sectors. Co-founder of ANDEL.",
        services_longevity_cta_title: "A Society That Lives Longer Needs Solutions for Life",
        services_longevity_cta_desc: "Understanding the life course allows us to anticipate needs, strengthen capacities, and design better opportunities for the present and the future.",
        services_longevity_cta_button: "Let’s Talk About Longevity",
        services_capabilities_title: "Capabilities That Strengthen Our Solutions",
        services_capabilities_desc: "We put cross-cutting capabilities at the service of every project to design, implement, measure, and scale solutions.",
        services_capability_1_title: "Innovation and Development",
        services_capability_1_desc: "We design ecosystems, models, and partnerships that connect stakeholders, strengthen organizations, and turn opportunities into sustainable solutions.",
        services_capability_1_tags: "Social innovation · Ecosystems · Business development · Governance · Coordination",
        services_capability_2_title: "Research, Data, and Behavior",
        services_capability_2_desc: "We generate evidence to understand people and territories, guide decisions, and improve results.",
        services_capability_2_tags: "Research · Data analytics · MEL · Behavioral sciences · Evaluation",
        services_capability_3_title: "Sustainability and Impact",
        services_capability_3_desc: "We integrate economic, social, and environmental dimensions to create sustainable value and measurable results.",
        services_capability_3_tags: "Sustainability · Value chains · Circular economy · Impact · Territorial development",
        services_capability_4_title: "Operational Capacity",
        services_capability_4_desc: "We complement our interventions with the management of goods, equipment, provisions, technology, and logistics when projects require it.",
        services_capability_4_tags: "Supply · Provisions · Technology · Logistics · Support",
        hero_btn_1: "Discover our solutions",
        hero_btn_2: "Let's talk about an alliance",

        // Index - Hero
        hero_title_p1: "More capabilities.<br />More opportunities.<br />More well-being.",
        hero_title_p2: "",
        hero_subtitle: "At MATE, we connect territories, people, and stakeholders to advance opportunities, transform realities hand in hand with communities, and foster well-being throughout life.",
        hero_btn_1: "Discover our solutions",
        hero_btn_2: "Let's talk about an alliance",

        // 1.2 About Us (Home)
        home_about_headline: "We are <span class='text-primary'>MATE</span>, a firm originating in Colombia that promotes economic inclusion with a territorial approach in Latin America.",
        home_about_subtext: "We work with public, private, cooperation entities, and local organizations to design and implement solutions that strengthen capacities, promote economic autonomy, and connect people with more and better opportunities.",
        home_about_btn: "Get to know us",

        // 1.3 Difference (Home)        
        home_diff_title: "Why are we different?",
        home_diff_subtitle: "We build comprehensive pathways that connect people, capacities, services, data, and alliances to generate sustainable changes.",
        home_diff_card1_title: "Passion with purpose",
        home_diff_card1_desc: "At MATE, we share a deep passion for what we do and direct it toward a common purpose: ensuring that people not only live MORE, but live in the BEST possible conditions of health, economic security, well-being, and quality of life.",
        home_diff_card2_title: "Purpose with direction",
        home_diff_card2_desc: "To achieve this purpose, we leverage rigorous, proven, and scientific methodologies, approaches, and techniques that keep us on course, grounding our actions in the best available evidence.",
        home_diff_card3_title: "Results with a social face",
        home_diff_card3_desc: "Beyond results measured through technical indicators, we are interested in measuring impact, making visible the transformations that take place within the social fabric.",
        home_diff_card4_title: "Quality with warmth",
        home_diff_card4_desc: "People will always be our highest value; therefore, our attention will remain centered on them, respecting their differences and the characteristics of each context and territory they inhabit.",

        // 1.4 What We Do (Home)
        home_do_title: "How do we do it?",
        home_do_subtitle: "Experience has taught us that people begin from different starting points and that every territory offers different opportunities. Therefore, at MATE, we first UNDERSTAND and then ACT.",

        home_do_card1_title: "Territorial and differentiated approach",
        home_do_card1_desc: "Starting from people and the opportunities within each territory, we tailor every intervention to diverse realities, capacities, and needs.",

        home_do_card2_title: "Comprehensive perspective",
        home_do_card2_desc: "We develop comprehensive and integrated perspectives by bringing together interdisciplinary teams of professionals with extensive experience and an empathetic approach.",

        home_do_card3_title: "Collaborative work",
        home_do_card3_desc: "We bring together the public sector, cooperation partners, companies, communities, and entrepreneurial ecosystems through an inter- and cross-sectoral approach.",

        home_do_card4_title: "Evidence-based decisions",
        home_do_card4_desc: "We integrate diagnostics, monitoring, data analytics, behavioral sciences, and implementation science to gain deeper insight and guide decision-making throughout execution.",

        home_do_card5_title: "Impact with purpose",
        home_do_card5_desc: "We pursue outcomes that strengthen well-being, autonomy, and real opportunities, ensuring that every stage of life becomes a firm step toward a new longevity.",

        home_do_btn: "See all solutions",

        // 1.5 Iniciativas (Home)
        home_init_title: "Initiatives marking our agenda today",
        init_tab_b: "Ethnic Model",
        init_tab_c: "MATE Foundation",
        init_tab_e: "Corporate Governance",
        init_content_b: "A commitment that integrates associativity, productive strengthening, cultural identity, and marketing channels.",
        init_content_c: "An initiative to mobilize alliances, philanthropy, and co-financing around economic inclusion and inclusive citizenship.",
        init_content_e: "A line of work aimed at supporting organizations—regardless of their size—in strengthening their corporate governance, promoting more robust, transparent, and sustainability-oriented leadership structures.",
        init_btn: "See solutions",

        // 1.6 Experience and Impact
        exp_title: "Experience and impact",
        exp_big_num: "+1'000.000",
        exp_big_label: "people impacted in Colombia",
        exp_btn: "Learn more",
        exp_desc: "Our experience combines fieldwork, capacity building, financial inclusion, applied research, and institutional articulation.",
        exp_stat1_num: "+500",
        exp_stat1_label: "enterprises",
        exp_stat2_num: "+100",
        exp_stat2_label: "communities",
        exp_stat3_num: "+50",
        exp_stat3_label: "partnerships",

        // Footer
        footer_desc: "We drive economic inclusion and inclusive citizenship through productive, financial, social, and sustainable solutions.",
        footer_links_title: "Links",
        footer_contact_title: "Contact",
        footer_location_1: "Bogotá D.C.",
        footer_location_2: "Montería, Córdoba",
        footer_location_3: "Colombia, South America",
        footer_rights: "© 2026 MATE Investments & Business SAS. All rights reserved.",
        developed_by: "Developed by",

        // --- PÁGINA: SOMOS MATE ---        

        // --- Hero Section ---
        hero_about_title: "We are MATE",
        hero_about_desc: "More than 10 years driving economic, financial, and social inclusion in Colombia and Latin America.",

        // --- About the company and Mission ---
        history_title: "Our History",
        history_text_1: "Ten years ago, MATE was born out of more than 23 years of experience transforming social policies and programs in Colombia and Latin America. We learned—and continue to learn—in the field, working alongside people, communities, organizations, and institutions, understanding their realities, capacities, and barriers. This experience has taught us that solutions must be DIVERSE: every territory, every community, and every person requires relevant and differentiated responses. That is why we design and implement solutions that connect capacities, stakeholders, and opportunities, and can be adapted and scaled.",
        history_text_2: "Today, we bring data analytics, behavioral and implementation sciences together with a vision of healthy longevity and new longevity, trusting that the support and power of information technologies will allow us to be more precise in understanding what works, for whom, and under which conditions.",
        history_text_3: "This is how we turn experience and evidence into solutions that create opportunities, transform realities, and make greater impact possible.",
        about_company_title: "About the Organization",
        about_company_subtitle: "Who are we?",
        about_company_text: "We are <strong>MATE</strong>, a Colombian consulting firm that drives social transformation through innovation. We turn <strong>capacities into opportunities and opportunities into better living conditions</strong>, connecting people, organizations, and territories to create lasting change. We design and implement solutions that combine <strong>territorial knowledge, evidence, experience, innovation, and technology</strong> to address complex social challenges and transform them into development opportunities.",
        mission_title: "Our Mission",
        mission_text: "We transform social and economic challenges into opportunities for development and fulfillment through the design and implementation of solutions that strengthen capacities, connect people, organizations, and territories, and create better conditions throughout the life course.",

        // How we work ---
        how_title: "How we work",
        how_c1_title: "We listen and understand",
        how_c1_desc: "We listen to communities, understand their needs, and analyze the territory and its context to identify capabilities, gaps, and opportunities.",
        how_c2_title: "We design action routes",
        how_c2_desc: "We jointly develop proposals tailored to the context, the people, and the objectives of each partnership.",
        how_c3_title: "We implement and support",
        how_c3_desc: "We develop processes with territorial proximity, training, technical assistance, and articulation.",
        how_c4_title: "We measure and learn",
        how_c4_desc: "We monitor, gather lessons learned, and adjust to improve results.",


        // --- Hitos Institucionales ---        
        hitos_title: "Institutional Milestones",
        recognition_badge: "International Recognition",
        recognition_text: "MATE received the recognition for Best Local Practice with a Gender Perspective within the framework of the VII Ibero-American Summit of Local Gender Agendas and the XV Ibero-American Congress of Municipalists, held in Zapopan, Mexico, in 2025, as a reflection of its commitment to inclusion, equity, and territorial transformation.",

        // Equipo 
        team_title: "Our Team",
        team_subtitle: "Meet the people driving the strategic vision and impact of MATE SAS.",

        team_p1_name: "Ana Milena Negrette",
        team_p1_role: "Founder and Chief Executive Officer",
        team_p1_bio: "Leads MATE's strategic vision and the consolidation of initiatives connecting territory, inclusion, and opportunities. She has over 22 years of experience in rural development, gender, entrepreneurship, and economic inclusion, supporting processes and vulnerable populations in Colombia and Latin America. She is a Business Administrator, holds a degree in Biology, Master's degrees in Rural Development and Gender, is a Specialist in Ecology, and has training in local economic development, entrepreneurship, and impact investing.",

        team_p2_name: "Any Andrea Benítez",
        team_p2_role: "Financial and social protection expert",
        team_p2_bio: "Expert in financial inclusion and social protection. She has over 22 years of experience in Colombia and Latin America, with an outstanding track record in financial education, savings, insurance, retirement savings, and the silver economy. She is an Agroindustrial Engineer, holds an MBA and a Master's degree in International Leadership, is a Specialist in Government, Management, and Public Affairs, and has training in corporate governance.",

        team_p3_name: "Ivonne Villada",
        team_p3_role: "Expert in financial inclusion, gender, and digital transformation",
        team_p3_bio: "Specialist in financial inclusion and social protection with over 16 years of experience in Latin America. She has led financial education, gender, and diversity initiatives to expand opportunities and access to financial services for vulnerable populations. She is an Environmental Administrator and holds a Master's degree in Rural Development, with training in local economic development, research, and the impact of public telecommunications policies in Latin America.",

        team_p4_name: "Claudia Sofía Santacruz",
        team_p4_role: "Projects Expert",
        team_p4_bio: "Expert in project planning and execution, coordination of multidisciplinary teams, and application of Monitoring, Evaluation, and Learning systems, risk management, and data-driven decision-making. She is an Industrial Engineer and Specialist in Engineering Management Systems with an emphasis on Projects and Production, with International Project Management training under PMBOK guidelines.",

        team_p5_name: "Estefany Brieva",
        team_p5_role: "Accounting and Financial Management Lead",
        team_p5_bio: "Leads the financial and accounting management of projects, contributing to administrative soundness and the control of internal processes. She is a Certified Public Accountant and Project Management Specialist.",

        team_p6_name: "Mauricio Romero Posada",
        team_p6_role: "Research, Monitoring and Evaluation Lead",
        team_p6_bio: "Anthropologist and Specialist in Solidarity Sector Business Management, with experience coordinating research and multidisciplinary teams in Latin America and Africa for social research, monitoring, and evaluation of development and economic and financial inclusion programs. Experienced in qualitative and quantitative methodologies, ethnographic research, and work with vulnerable and diverse populations.",

        team_p7_name: "José Carlos Zapa",
        team_p7_role: "National Territorial Lead",
        team_p7_bio: "Business Administrator, music educator, and Project Management Specialist, with experience in business development, organizational strengthening, and the economic and financial inclusion of productive projects. His career is grounded in territorial management and the implementation of projects across diverse regions of Colombia.",

        team_p8_name: "Martha Rengifo",
        team_p8_role: "Southwestern Territorial Lead",
        team_p8_bio: "Business Administrator, Tourism and Hospitality Administrator, and Market Manager, with experience in strategic management, business and territorial development, commercial management, productive value-chain strengthening, institutional coordination, support for organizations and communities, and market intelligence. She brings a differentiated and territorial development approach.",

        team_p10_name: "Claudia Negrete Contreras",
        team_p10_role: "Caribbean Territorial Lead",
        team_p10_bio: "Graduate in Educational Informatics and Audiovisual Media and Specialist in Educational Information Technology Administration, with experience in territorial management, education, social and community support, and project coordination. She has worked with children, adolescents, young people, families, and communities, as well as in data collection and follow-up, logistical and administrative management, and coordination with community stakeholders, incorporating pedagogical and technological tools into intervention processes.",

        team_p11_name: "Erick Sebastián Bermúdez Rodríguez",
        team_p11_role: "Process and Data Management",
        team_p11_bio: "Industrial Engineer and Project Management Specialist, with experience in strategic planning, project monitoring and control, and organizational process optimization. He has experience in simplifying complex systems, designing monitoring and evaluation tools, managing large-scale data-capture processes, and analyzing data for decision-making, ensuring traceability, quality, and timely information.",

        // -- Alliances ---
        alliances_title: "I am because WE ARE: the power of alliances",
        alliances_text: "We build strategic alliances with organizations that complement our experience and enable us to integrate new capabilities, methodologies, and technologies to address increasingly complex challenges.",
        alliances_card1_title: "UT FINCLUSIÓN",
        alliances_card1_partner: "MATE + INSTINTIVO",
        alliances_card1_desc: "Financial inclusion, behavioral sciences, and innovation.",
        alliances_visit_instintivo: "Discover Instintivo",
        alliances_card2_title: "UT IMPACTO 50+",
        alliances_card2_partner: "MATE + INSTINTIVO + ZELVA",
        alliances_card2_desc: "Longevity, silver economy finance, behavioral sciences, user experience, and communications.",
        alliances_instintivo_link: "Discover Instintivo",
        alliances_zelva_link: "Discover Zelva",
        alliances_card3_title: "PropulXora",
        alliances_card3_partner: "MATE + PROPULSOR LATINOAMÉRICA",
        alliances_card3_desc: "An alliance between MATE and Propulsor Latinoamérica to strengthen businesses through technology, business intelligence, innovation, and access to finance.",
        alliances_propulsor_link: "Discover Propulsor",
        alliances_card4_title: "Fondo Mujer",
        alliances_card4_desc: "Participation as technical partners and speakers in women’s entrepreneurship strengthening initiatives.",
        alliances_fondo_mujer_link_1: "Watch the conference: Women Microentrepreneurs: Challenges and Barriers",
        alliances_fondo_mujer_link_2: "Watch the conference: Savings and Longevity: Toward Aging with Autonomy and Well-Being",
        alliances_card5_title: "ANDEL",
        alliances_card5_desc: "MATE is part of the National Association of Local Development Agencies (ANDEL), a network that promotes territorial economic development through collaboration among governments, businesses, academia, and social organizations.",
        alliances_card5_note: "Participation in national discussions on the longevity economy.",
        alliances_card6_title: "Corporate Governance",
        alliances_card6_desc: "MATE actively contributes to building better corporate governance practices.",
        alliances_card6_item1: "Institutional participation",
        alliances_card6_item2: "Members of the Board of Directors of Uniandinos’ Corporate Governance Study Group.",
        alliances_card6_item3: "Design and implementation of governance models for businesses, social organizations, and public-private partnerships.",
        alliances_card6_item4: "Leadership networks.",
        alliances_quote: "\"The right alliances turn an intention into sustainable transformation.\"",

        // --- PÁGINA: PROYECTOS ---
        // --- Hero Section ---
        hero_proj_title: "Experience translated into action",
        hero_proj_desc: "Our experience combines fieldwork, capacity building, financial inclusion, applied research, and institutional articulation.",

        // Services/Projects Detail        
        serv_muelle_title: "Buenaventura Tourist Pier (2017–2023)",
        serv_muelle_desc: "Design and implementation of the concession plan, integrating operational modernization and social support. Structuring the coordination with key actors and strengthening strategic management, processes and risks. Development of user experience strategies, financial education and access to financial products for the pier community.",

        serv_a_title: "Ethnic Woman",
        serv_a_desc: "A methodology developed by MATE to strengthen women-led enterprises in ethnic communities, integrating cultural identity, business development, financial inclusion, productive assets, and market access.",
        serv_a_flow_1: "Understand",
        serv_a_flow_2: "Strengthen",
        serv_a_flow_3: "Advance",
        serv_a_flow_4: "Connect",
        serv_a_flow_5: "Consolidate",

        serv_b_title: "Banca de las Oportunidades",
        serv_b_desc: "We developed strategic recommendations for the design of savings programs aimed at low-income and/or vulnerable populations.",

        serv_c_title: "Rural youth migration",
        serv_c_desc: "We led research on the factors affecting the migration of rural youth, generating inputs for decisions and policies with a territorial focus.",

        serv_d_title: "Familias en su Tierra",
        serv_d_desc: "We supported return processes for conflict-victim households with actions in food security, housing, and income generation.",

        serv_e_title: "Bancalimentos Alliance",
        serv_e_desc: "We developed and adapted inclusive financial products for vulnerable populations, articulating channels, incentives, communication, and field validation.",

        serv_f_title: "Digital financial education for women in Chile",
        serv_f_desc: "We designed and adapted a digital financial education product for vulnerable women in Chile, with a pedagogical and behavioral focus.",

        cta_capitaliza_title: "Capitalize your business",
        cta_capitaliza_text: "We help you value your venture and explore financing options.",

        // --- CONTACT PAGE ---
        hero_contact_title: "Let's talk about your next project",
        hero_contact_desc: "We are ready to listen to your needs and build solutions with territorial and social impact together.",
        contact_info_title: "Contact Information",
        contact_info_desc: "Complete the form and our team will get in touch with you.",
        contact_write_us: "Write to us",
        contact_call_us: "WhatsApp",
        contact_location_label: "Location",
        contact_follow_us: "Follow us",

        // Form
        form_name: "Full name",
        form_name_placeholder: "Your name",
        form_entity: "Company / Entity",
        form_entity_placeholder: "Your organization name",
        form_email: "Email address",
        form_email_placeholder: "youremail@example.com",
        form_phone: "Contact phone",
        form_phone_placeholder: "Ex: +57 300 123 4567",
        form_subject: "Subject",
        opt_alliance: "Partnership Proposal",
        opt_consulting: "Consulting / Services",
        opt_info: "Information Request",
        opt_other: "Other",
        form_message: "Message",
        form_message_placeholder: "Tell us more about how we can help you...",
        form_privacy_text: "I accept the",
        form_privacy_link: "Data Privacy Policy",
        form_btn: "Send Message",
        form_sending: "Sending...",
        form_success: "Thank you. Your message was sent for processing. We will be in touch shortly.",
        form_error: "We could not send your message. Please check your connection and try again later.",

        // Security Validation (Captcha)
        captcha_label: "Security validation: What is ",
        captcha_placeholder: "Your answer",
        captcha_error: "The security answer is incorrect.",

        contact_follow_us: "Follow us",
        social_instagram: "Visit Instagram",
        social_linkedin: "Visit LinkedIn",

    }
};
